site_name: Turnstile OctoberCMS Plugin
site_description: Documentation for the Turnstile CAPTCHA plugin for OctoberCMS
site_author: Depcore
repo_url: https://github.com/DEPCORE-PL/turnstile-plugin
docs_dir: docs

plugins:
  - search

